name: Build and test for PR

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test-pr:
    runs-on: ubuntu-latest
    container: rostooling/setup-ros-docker:ubuntu-focal-ros-galactic-ros-base-latest

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # Fetch with depth=0 to calculate modified packages
          fetch-depth: 0

      - name: Install pip
        run: |
          apt-get -y update
          apt-get -y install python3-pip

      # tmp: colcon-package-selection 0.2.6 doesn't support --packages-above-and-dependencies
      - name: Update colcon
        run: |
          pip3 install -U colcon-package-selection

      - name: Search modified packages
        id: list_packages
        run: |
          ${GITHUB_WORKSPACE}/.github/get_modified_package.sh origin/${{ github.base_ref }}

      - name: Show target packages
        run: |
          echo "Target packages: ${{ steps.list_packages.outputs.package_list }}"

      - name: Set git config for private repositories
        if: ${{ steps.list_packages.outputs.package_list != '' }}
        run: |
          git config --local --unset-all http.https://github.com/.extraheader || true
          git config --global url.https://${{ secrets.REPO_TOKEN }}@github.com.insteadOf 'https://github.com'

      - name: Clone dependency packages
        if: ${{ steps.list_packages.outputs.package_list != '' }}
        run: |
          mkdir dependency_ws
          vcs import dependency_ws < build_depends.repos
          apt-get -y update
          rosdep update
          DEBIAN_FRONTEND=noninteractive rosdep install -y --from-paths . --ignore-src --rosdistro galactic

      - name: Build
        if: ${{ steps.list_packages.outputs.package_list != '' }}
        run: |
          . /opt/ros/galactic/setup.sh
          colcon build --event-handlers console_cohesion+ \
            --packages-above-and-dependencies ${{ steps.list_packages.outputs.package_list }} \
            --cmake-args -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Run tests
        if: ${{ steps.list_packages.outputs.package_list != '' }}
        run: |
          . /opt/ros/galactic/setup.sh
          colcon test --event-handlers console_cohesion+ \
            --packages-above ${{ steps.list_packages.outputs.package_list }} \
            --return-code-on-test-failure
