/**:
  ros__parameters:
    N: 6
    H: 1080
    W: 1920
    ModelConfig: ./cfgs/bevdet_6camera.yaml
    ImgStageEngine: ./model/img_stage_lt_d_fp16.engine
    BEVStageEngine: ./model/bev_stage_lt_d_fp16.engine
    CamConfig: /sample0/sample0000.yaml
    OutputLidarBox: /sample0/sample0_lidarbox.txt
    cams: [CAM_FRONT_RIGHT, CAM_FRONT_LEFT, CAM_BACK_RIGHT, CAM_FRONT, CAM_BACK_LEFT, CAM_BACK]
