# Area query for map loading
# (PCD grids that overlaps with the area is going to be loaded)
AreaInfo area

---
# Header
std_msgs/Header header

# Newly loaded PCD maps with ID
PointCloudMapCellWithID[] new_pointcloud_with_ids
