/**:
  ros__parameters:
    simulated_frame_id: "base_link"
    origin_frame_id: "map"
    # Option for vehicle_model_type:
    # - IDEAL_STEER_VEL : reads velocity command. The steering and acceleration changes exactly the same as commanded.
    # - IDEAL_STEER_ACC : reads acceleration command. The steering and acceleration changes exactly the same as commanded.
    # - IDEAL_STEER_ACC_GEARED : reads acceleration command. The steering and acceleration changes exactly the same as commanded and consider the gear command.
    # - DELAY_STEER_VEL : reads velocity command. The steering and velocity changes with delay model.
    # - DELAY_STEER_ACC : reads acceleration command. The steering and acceleration changes with delay model.
    # - DELAY_STEER_ACC_GEARED : reads acceleration command. The steering and acceleration changes with delay model and consider the gear command.
    vehicle_model_type: "DELAY_STEER_VEL"
    initialize_source: "INITIAL_POSE_TOPIC"
    timer_sampling_time_ms: 25
    add_measurement_noise: False

    vel_lim: 5.28
    vel_rate_lim: 7.0
    vel_time_constant: 0.61
    vel_time_delay: 0.25

    steer_lim: 0.645
    steer_rate_lim: 5.0
    steer_time_constant: 0.10
    steer_time_delay: 0.14

    acc_time_delay: 0.1
    acc_time_constant: 0.1
    acc_time_constant: 0.1
    acc_time_delay: 0.1

    x_stddev: 0.0001 # x standard deviation for dummy covariance in map coordinate
    y_stddev: 0.0001 # y standard deviation for dummy covariance in map coordinate
