default:
  # This file defines the parameters for the linear motion tracker.
  # All this parameter coordinate is assumed to be in the vehicle coordinate system.
  # So, the x axis is pointing to the front of the vehicle, y axis is pointing to the left of the vehicle.
  ekf_params:
    # random walk noise is used to model the acceleration noise
    process_noise_std: # [m/s^2]
      ax: 0.98 # assume 0.1G acceleration noise
      ay: 0.98
      vx: 1.0 # assume 1m/s velocity noise
      vy: 1.0
      x: 1.0 # assume 1m position noise
      y: 1.0
    measurement_noise_std:
      x: 0.6 # [m]
      # y: 4.0 # [m]
      y: 0.01 # rad/m if use_polar_coordinate_in_measurement_noise is true
      vx: 10 # [m/s]
      vy: 100 # [m/s]
    initial_covariance_std:
      x: 3.0 # [m]
      y: 6.0 # [m]
      vx: 1000.0 # [m/s]
      vy: 1000.0 # [m/s]
      ax: 1000.0 # [m/s^2]
      ay: 1000.0 # [m/s^2]
    estimate_acc: false # set true if you want to estimate the acceleration
  # input flag
  trust_yaw_input: false # set true if yaw input of sensor is reliable
  trust_twist_input: false # set true if twist input of sensor is reliable
  use_polar_coordinate_in_measurement_noise: true # set true if you want to define the measurement noise in polar coordinate
  # output limitation
  limit:
    max_speed: 80.0 # [m/s]
  # low pass filter is used to smooth the yaw and shape estimation
  low_pass_filter:
    time_constant: 1.0 # [s]
    sampling_time: 0.1 # [s]
