/**:
  ros__parameters:
    msg_type_target: "autoware_auto_control_msgs/msg/AckermannControlCommand"
    topic_name_source: "/control/command/control_cmd"
    topic_name_target: "/control/command/control_cmd_auto"
