# Area query for map loading
# (PCD grids that overlaps with the area is going to be loaded)
AreaInfo area

# The IDs of PCD maps that the node already has
string[] cached_ids

---
# Header
std_msgs/Header header

# Newly loaded PCD maps with ID
PointCloudMapCellWithID[] new_pointcloud_with_ids

# Map IDs that the client side should remove
string[] ids_to_remove
