cpu_affinity:
  /pointcloud_container: 8,9,10,11
  /sensing/lidar/top/pointcloud_preprocessor/velodyne_node_container: 0,1
env: /home/orin/autoware/tmp/env.sh
flag: 'True'
redundant_info:
  root@192.168.4.2@:
  - /system/system_monitor/system_monitor_container
  root@192.168.4.4@:
  - /system/system_monitor/system_monitor_container
remote_info:
  root@192.168.4.2:
  - /planning/mission_planning/mission_planner
  - /planning/mission_planning/goal_pose_visualizer
  - /planning/scenario_planning/scenario_selector
  - /planning/scenario_planning/external_velocity_limit_selector
  - /planning/scenario_planning/motion_velocity_smoother
  - /planning/scenario_planning/lane_driving/behavior_planning/behavior_planning_container
  - /planning/scenario_planning/lane_driving/behavior_planning/rtc_auto_mode_manager
  - /planning/scenario_planning/lane_driving/motion_planning/motion_planning_container
  - /planning/scenario_planning/parking/parking_container
  - /planning/planning_diagnostics/planning_error_monitor
  root@192.168.4.3:
  - /sensing/lidar/top/pointcloud_preprocessor/velodyne_node_container
  - /pointcloud_container
  - /control/control_container
  root@192.168.4.4:
  - /map/map_container
  - /map/map_hash_generator
  - /sensing/imu/imu_corrector
  - /sensing/gnss/gnss_poser
  - /sensing/vehicle_velocity_converter_node
  - /localization/util/map_height_fitter
  - /localization/util/pose_initializer_node
  - /localization/util/default_ad_api/helpers/automatic_pose_initializer
  - /localization/twist_estimator/gyro_odometer
  - /localization/pose_twist_fusion_filter/ekf_localizer
  - /localization/pose_twist_fusion_filter/stop_filter
  - /localization/pose_twist_fusion_filter/twist2accel
  - /localization/localization_error_monitor
  - /perception/object_recognition/detection/clustering/euclidean_cluster_container
  - /perception/object_recognition/detection/clustering/shape_estimation
  - /perception/object_recognition/detection/clustering/detected_object_feature_remover
  - /perception/object_recognition/detection/detection_by_tracker/detection_by_tracker_node
  - /perception/object_recognition/detection/centerpoint/lidar_centerpoint
  - /perception/object_recognition/detection/obstacle_pointcloud_based_validator_node
  - /perception/object_recognition/detection/object_lanelet_filter
  - /perception/object_recognition/tracking/multi_object_tracker
  - /perception/object_recognition/prediction/map_based_prediction
  - /perception/traffic_light_recognition/traffic_light_map_based_detector
  - /perception/traffic_light_recognition/traffic_light_node_container
  - /perception/traffic_light_recognition/traffic_light_map_visualizer
  - /perception/object_recognition/detection/object_association_merger
restart_info:
  root@192.168.4.3@:
  - /pointcloud_container
  - /sensing/lidar/top/pointcloud_preprocessor/velodyne_node_container
  root@192.168.4.4@:
  - /pointcloud_container
  - /sensing/lidar/top/pointcloud_preprocessor/velodyne_node_container