/**:
  ros__parameters:
    map_frame: "map"
    base_link_frame: "base_link"
    output_frame: "base_link"
    # using top of the main lidar frame is appropriate. ex) velodyne_top

    use_height_filter: true
    enable_single_frame_mode: false
    map_length: 100.0
    map_width: 100.0
    map_resolution: 0.5
    input_obstacle_pointcloud: true
    input_obstacle_and_raw_pointcloud: true
