uint8 NONE = 0
uint8 NEUTRAL = 1
uint8 DRIVE = 2
uint8 DRIVE_2 = 3
uint8 DRIVE_3 = 4
uint8 DRIVE_4 = 5
uint8 DRIVE_5 = 6
uint8 DRIVE_6 = 7
uint8 DRIVE_7 = 8
uint8 DRIVE_8 = 9
uint8 DRIVE_9 = 10
uint8 DRIVE_10 = 11
uint8 DRIVE_11 = 12
uint8 DRIVE_12 = 13
uint8 DRIVE_13 = 14
uint8 DRIVE_14 = 15
uint8 DRIVE_15 = 16
uint8 DRIVE_16 = 17
uint8 DRIVE_17 = 18
uint8 DRIVE_18 = 19
uint8 REVERSE = 20
uint8 REVERSE_2 = 21
uint8 PARK = 22
uint8 LOW = 23
uint8 LOW_2 = 24

builtin_interfaces/Time stamp
uint8 report
