/**:
  ros__parameters:
    planning:
      type: diagnostic_aggregator/AnalyzerGroup
      path: planning
      analyzers:
        node_alive_monitoring:
          type: diagnostic_aggregator/AnalyzerGroup
          path: node_alive_monitoring
          analyzers:
            topic_status:
              type: diagnostic_aggregator/GenericAnalyzer
              path: topic_status
              contains: [": planning_topic_status"]
              timeout: 1.0

        performance_monitoring:
          type: diagnostic_aggregator/AnalyzerGroup
          path: performance_monitoring
          analyzers:
            trajectory_validation:
              type: diagnostic_aggregator/AnalyzerGroup
              path: trajectory_validation
              analyzers:
                trajectory_finite_value:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: trajectory_validation_finite
                  contains: [": trajectory_validation_finite"]
                  timeout: 1.0

                trajectory_interval:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: trajectory_validation_interval
                  contains: [": trajectory_validation_interval"]
                  timeout: 1.0

                trajectory_curvature:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: trajectory_validation_curvature
                  contains: [": trajectory_validation_curvature"]
                  timeout: 1.0

                trajectory_sharp_angle:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: trajectory_validation_relative_angle
                  contains: [": trajectory_validation_relative_angle"]
                  timeout: 1.0

                trajectory_relative_angle:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: trajectory_validation_relative_angle
                  contains: [": trajectory_validation_relative_angle"]
                  timeout: 1.0

                trajectory_lateral_acceleration:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: trajectory_validation_lateral_acceleration
                  contains: [": trajectory_validation_lateral_acceleration"]
                  timeout: 1.0

                trajectory_acceleration:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: trajectory_validation_acceleration
                  contains: [": trajectory_validation_acceleration"]
                  timeout: 1.0

                trajectory_deceleration:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: trajectory_validation_deceleration
                  contains: [": trajectory_validation_deceleration"]
                  timeout: 1.0

                trajectory_steering:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: trajectory_validation_steering
                  contains: [": trajectory_validation_steering"]
                  timeout: 1.0

                trajectory_steering_rate:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: trajectory_validation_steering_rate
                  contains: [": trajectory_validation_steering_rate"]
                  timeout: 1.0

                trajectory_velocity_deviation:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: trajectory_validation_velocity_deviation
                  contains: [": trajectory_validation_velocity_deviation"]
                  timeout: 1.0
