/**:
  ros__parameters:
    lanelet2_map_projector_type: MGRS   # Options: MGRS, UTM
    latitude: 40.816617984672746        # Latitude of map_origin, using in UTM
    longitude: 29.360491808334285       # Longitude of map_origin, using in UTM

    center_line_resolution: 5.0         # [m]
