/**:
  ros__parameters:
    backward_path_length: 5.0
    forward_path_length: 300.0
    backward_length_buffer_for_end_of_lane: 5.0
    backward_length_buffer_for_end_of_pull_over: 5.0
    backward_length_buffer_for_end_of_pull_out: 5.0
    minimum_lane_change_length: 12.0
    minimum_pull_over_length: 16.0
    refine_goal_search_radius_range: 7.5
    turn_signal_intersection_search_distance: 30.0
    turn_signal_intersection_angle_threshold_deg: 15.0
    turn_signal_minimum_search_distance: 10.0
    turn_signal_search_time: 3.0
    turn_signal_shift_length_threshold: 0.3
    turn_signal_on_swerving: true
    path_interval: 2.0
