/**:
  ros__parameters:
    max_vibration_pitch: 0.00436332312   # -0.5 ~ 0.5 deg
    max_vibration_yaw: 0.00436332312     # -0.5 ~ 0.5 deg
    max_vibration_height: 0.01           # -0.05 ~ 0.05 m
    max_vibration_width: 0.01            # -0.05 ~ 0.05 m
    max_vibration_depth: 0.01            # -0.05 ~ 0.05 m
