sensor_kit_base_link:
  camera0/camera_link:
    x: 3.9
    y: 0.0
    z: 0.9
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  camera1/camera_link:
    x: 1.0
    y: 1.1
    z: 0.9
    roll: 0.0
    pitch: 0.0
    yaw: 1.57
  camera2/camera_link:
    x: 1.0
    y: -1.0
    z: 0.9
    roll: 0.0
    pitch: 0.0
    yaw: -1.57
  camera3/camera_link:
    x: -1.05
    y: 0.0
    z: 0.9
    roll: 0.0
    pitch: 0.0
    yaw: -3.14
  camera4/camera_link:
    x: 0.07356
    y: 0.0
    z: -0.0525
    roll: 0.0
    pitch: -0.03
    yaw: -0.005
  camera5/camera_link:
    x: -0.07356
    y: 0.0
    z: -0.0525
    roll: 0.0
    pitch: -0.01
    yaw: 3.125
  # traffic_light_right_camera/camera_link:
  #   x: 0.05
  #   y: -0.0175
  #   z: -0.1
  #   roll: 0.0
  #   pitch: 0.0
  #   yaw: 0.0
  # traffic_light_left_camera/camera_link:
  #   x: 0.05
  #   y: 0.0175
  #   z: -0.1
  #   roll: 0.0
  #   pitch: 0.0
  #   yaw: 0.0
  velodyne_top_base_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  # velodyne_left_base_link:
  #   x: 0.0
  #   y: 0.56362
  #   z: -0.30555
  #   roll: -0.02
  #   pitch: 0.71
  #   yaw: 1.575
  # velodyne_right_base_link:
  #   x: 0.0
  #   y: -0.56362
  #   z: -0.30555
  #   roll: -0.01
  #   pitch: 0.71
  #   yaw: -1.580
  gnss_link:
    x: -0.1
    y: 0.0
    z: -0.2
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  tamagawa/imu_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: -1.57
