base_link:
  sensor_kit_base_link:
    x: 1.0
    y: 0.0
    z: 1.8
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  # velodyne_rear_base_link:
  #   x: -0.358
  #   y: 0.0
  #   z: 1.631
  #   roll: -0.02
  #   pitch: 0.7281317
  #   yaw: 3.141592
