/**:
  ros__parameters:
    enable_delay_compensation: true
    prediction_time_horizon: 10.0 #[s]
    prediction_sampling_delta_time: 0.5 #[s]
    min_velocity_for_map_based_prediction: 1.39 #[m/s]
    min_crosswalk_user_velocity: 1.39 #[m/s]
    dist_threshold_for_searching_lanelet: 3.0 #[m]
    delta_yaw_threshold_for_searching_lanelet: 0.785 #[rad]
    sigma_lateral_offset: 0.5 #[m]
    sigma_yaw_angle_deg: 5.0 #[angle degree]
    object_buffer_time_length: 2.0 #[s]
    history_time_length: 1.0 #[s]
    dist_threshold_for_lane_change_detection: 1.0 #[m]
    time_threshold_for_lane_change_detection: 5.0 #[s]
    cutoff_freq_of_velocity_for_lane_change_detection: 0.1 #[Hz]
    reference_path_resolution: 0.5 #[m]
