version: 2
jobs:
  foxy:
    docker:
      - image: ros:foxy

    working_directory: ~/rtklib_ros_bridge

    steps:
      - checkout

      - run:
          name: Setup dependency
          command: |
            apt-get update -qq
            apt-get install -y software-properties-common
            apt-get install -y -qq --no-install-recommends python3-vcstool
            source /opt/ros/foxy/setup.bash
            mkdir ~/tmp
            ln -s ~/project ~/tmp/src
            cd ~/tmp
            rosdep install --from-paths . --ignore-src -y
      - run:
          name: Build
          command: |
            source /opt/ros/foxy/setup.bash
            mkdir -p ~/tmp/ws/src
            ln -s `pwd` ~/tmp/ws/src/package
            cd ~/tmp/ws/
            colcon build
workflows:
  version: 2
  ros_build:
    jobs:
      - foxy
